import * as icon from "react-icons/fa";
import { SquareThemeData } from "../../interfaces/SquareThemeData";

export const BoardTheme = new Map<number, SquareThemeData>();

BoardTheme.set(1, { name: "Go", msg: "Collect $200.00 salary as you pass", icon: <icon.FaLongArrowAltLeft className="drawing" /> });
BoardTheme.set(2, { name: "Mediter- ranean Avenue", price: 50 });
BoardTheme.set(3, { name: "Community Chest", msg: "Follow instructions on top card", icon: <icon.FaCube className="drawing text-blue-300" /> });
BoardTheme.set(4, { name: "Baltic Avenue", price: 50 });
BoardTheme.set(5, { name: "Income Tax", msg: "Pay 10% or $200", other: true, });
BoardTheme.set(6, { name: "Reading Railroad", price: 200, icon: <icon.FaSubway className="drawing" /> });
BoardTheme.set(7, { name: "Oriental Avenue", price: 100 });
BoardTheme.set(8, { name: "Chance", icon: <icon.FaQuestion className="drawing" /> });
BoardTheme.set(9, { name: "Vermont Avenue", price: 100 });
BoardTheme.set(10, { name: "Connecti- cut Avenue", price: 120 });

BoardTheme.set(12, { name: "St. Charles Place", price: 140  });
BoardTheme.set(13, { name: "Electric Company", price: 150, icon: <icon.FaLightbulb className="drawing text-yellow-300" /> });
BoardTheme.set(14, { name: "States Avenue", price: 140  });
BoardTheme.set(15, { name: "Virginia Avenue", price: 160  });
BoardTheme.set(16, { name: "Pennsylvania Railroad", price: 200, icon: <icon.FaSubway className="drawing" /> });
BoardTheme.set(17, { name: "St. James Avenue", price: 180 });
BoardTheme.set(18, { name: "Community Chest", msg: "Follow instructions on top card", icon: <icon.FaCube className="drawing text-blue-300" /> });
BoardTheme.set(19, { name: "Tennessee Avenue", price: 180 });
BoardTheme.set(20, { name: "New York Avenue", price: 200 });
BoardTheme.set(21, { name: "Free", msg: "Parking", icon: <icon.FaCar className="drawing" /> });
BoardTheme.set(22, { name: "Kentucky Avenue", price: 220 });
BoardTheme.set(23, { name: "Chance", icon: <icon.FaQuestion className="drawing" /> });
BoardTheme.set(24, { name: "Indiana Avenue", price: 220 });
BoardTheme.set(25, { name: "Illinois Avenue", price: 200 });
BoardTheme.set(26, { name: "B & O Railroad", price: 200, icon: <icon.FaSubway className="drawing" /> });
BoardTheme.set(27, { name: "Atlantic Avenue", price: 260 });
BoardTheme.set(28, { name: "Ventnor Avenue", price: 260 });
BoardTheme.set(29, { name: "Waterworks", price: 120, icon: <icon.FaTint className="drawing  text-blue-800" /> });
BoardTheme.set(30, { name: "Marvin Gardens", price: 280 });
BoardTheme.set(31, { name: "Go to", msg: "Jail", icon: <icon.FaGavel className="drawing" /> });
BoardTheme.set(32, { name: "Pacific Avenue", price: 300 });
BoardTheme.set(33, { name: "North Carolina Avenue", price: 300 });
BoardTheme.set(34, { name: "Community Chest", msg: "Follow instructions on top card", icon: <icon.FaCube className="drawing text-blue-300" /> });
BoardTheme.set(35, { name: "Pennsylva- nia Avenue", price: 320 });
BoardTheme.set(36, { name: "Short Line", price: 200, icon: <icon.FaSubway className="drawing" />  });
BoardTheme.set(37, { name: "Chance", icon: <icon.FaQuestion className="drawing  text-blue-700" /> });
BoardTheme.set(38, { name: "Park Place", price: 350 });
BoardTheme.set(39, { name: "Luxury Tax", msg: "Pay $75.00", icon: <icon.FaGem className="drawing text-black" /> });
BoardTheme.set(40, { name: "Boardwalk", price: 400 });